<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputPath>bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendConfigurationToOutputPath>false</AppendConfigurationToOutputPath>
	</PropertyGroup>



	<ItemGroup>
		<ProjectReference Include="..\DalFacade\DalFacade.csproj" />
		<ProjectReference Include="..\DalList\DalList.csproj" />
	</ItemGroup>

</Project>

